--Just putting these here for refreshing later.
DROP TABLE BANKACCOUNTS;

CREATE TABLE BANKACCOUNTS(
	ACNTNUM NUMBER(10) PRIMARY KEY,
	ACNTTYPE varchar2(255) NOT NULL check(LENGTH(acntType) > 1),
	FIRSTNAME varchar2(255) NOT NULL check(LENGTH(FIRSTNAME) > 1),
	LASTNAME varchar2(255) NOT NULL check(LENGTH(LASTNAME) > 1),
	USERNAME varchar2(255) NOT NULL check(LENGTH(USERNAME) > 1),
	PASSWORD varchar2(255) NOT NULL check(LENGTH(PASSWORD) > 1),
	BALANCE DECIMAL(38, 2)
);

DROP SEQUENCE bank_seq;

CREATE SEQUENCE bank_seq
	START WITH 100000
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER bank_seq_trigger
BEFORE INSERT ON BANKACCOUNTS
FOR EACH ROW
BEGIN
	IF : NEW.ACNTNUM IS NULL THEN
	SELECT bank_seq.nextval INTO : NEW.ACNTNUM FROM dual;
	END IF;
END;

INSERT INTO BANKACCOUNTS(ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE)
VALUES(1000000, 'CUSTOMER', 'John', 'Jacobsen', 'jj_number1', 'isTHISaGOODpassword?', 100001.28);

INSERT INTO BANKACCOUNTS(ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE)
VALUES(100001, 'CUSTOMER', 'John', 'Jacobs', 'jj', '1234', 100001.28);

INSERT INTO BANKACCOUNTS(ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE)
VALUES(999999, 'ADMIN', 'Tom', 'Rogers', 'Adminboi', 'secure', 25000);

SELECT * FROM BANKACCOUNTS;

DELETE FROM BANKACCOUNTS WHERE ACNTNUM = 100001;

DELETE FROM BANKACCOUNTS
WHERE FIRSTNAME = 'John';

DELETE FROM BANKACCOUNTS
WHERE ACNTNUM = 100001;

CREATE OR REPLACE PROCEDURE create_account(ACNTNUM OUT NUMBER, ACNTTYPE IN varchar2, FIRSTNAME IN varchar2, LASTNAME IN varchar2, USERNAME IN varchar2, PASSWORD IN varchar2, BALANCE IN DECIMAL)
IS
BEGIN
   INSERT INTO BANKACCOUNTS (ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE) VALUES (bank_seq.nextval, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE);
   ACNTNUM := bank_seq.currval;
  COMMIT;
END;