--Just putting these here for refreshing later.
DROP TABLE BANKACCOUNTS;

DROP TABLE TRANSACTIONS;

CREATE TABLE BANKACCOUNTS(
	ACNTNUM NUMBER(10) PRIMARY KEY,
	ACNTTYPE varchar2(255) NOT NULL check(LENGTH(acntType) > 1),
	FIRSTNAME varchar2(255) NOT NULL check(LENGTH(FIRSTNAME) > 1),
	LASTNAME varchar2(255) NOT NULL check(LENGTH(LASTNAME) > 1),
	USERNAME varchar2(255) NOT NULL check(LENGTH(USERNAME) > 1),
	PASSWORD varchar2(255) NOT NULL check(LENGTH(PASSWORD) > 1),
	BALANCE DECIMAL(38, 2)
);

CREATE TABLE TRANSACTIONS(
	TRANSID NUMBER(10) PRIMARY KEY,
	TRANS varchar2(255) NOT NULL check(LENGTH(TRANS) > 1),
	AMOUNT DECIMAL(38, 2) NOT NULL,
	ACNTNUM_ID NUMBER(10) NOT NULL,
	CONSTRAINT TRANSACTIONS_BANKACCOUNTS FOREIGN KEY (ACNTNUM_ID)
		REFERENCES BANKACCOUNTS (ACNTNUM) ON DELETE CASCADE
);

SELECT * FROM TRANSACTIONS;

SELECT * FROM BANKACCOUNTS;

DROP SEQUENCE bank_seq;

CREATE SEQUENCE bank_seq
	START WITH 100000
	INCREMENT BY 1;


CREATE OR REPLACE TRIGGER bank_seq_trigger
BEFORE INSERT ON BANKACCOUNTS
FOR EACH ROW
BEGIN
	IF : NEW.ACNTNUM IS NULL THEN
	SELECT bank_seq.nextval INTO : NEW.ACNTNUM FROM dual;
	END IF;
END;

CREATE SEQUENCE trans_seq
	START WITH 1
	INCREMENT BY 1;


DROP SEQUENCE trans_seq;

CREATE OR REPLACE TRIGGER trans_seq_trigger
BEFORE INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
	IF : NEW.TRANSID IS NULL THEN
	SELECT trans_seq.nextval INTO : NEW.TRANSID FROM dual;
	END IF;
END;

INSERT INTO BANKACCOUNTS(ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE)
VALUES(1000000, 'CUSTOMER', 'John', 'Jacobsen', 'jj_number1', 'isTHISaGOODpassword?', 100001.28);

INSERT INTO BANKACCOUNTS(ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE)
VALUES(100001, 'CUSTOMER', 'John', 'Jacobs', 'jj', '1234', 100001.28);

INSERT INTO BANKACCOUNTS(ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE)
VALUES(999999, 'ADMIN', 'Tom', 'Rogers', 'Adminboi', 'secure', 25000);

SELECT * FROM BANKACCOUNTS;

DELETE FROM BANKACCOUNTS WHERE ACNTNUM = 100001;

DELETE FROM BANKACCOUNTS
WHERE FIRSTNAME = 'John';

DELETE FROM BANKACCOUNTS
WHERE ACNTNUM = 100001;

DELETE FROM TRANSACTIONS
WHERE TRANSID = 1;


CREATE OR REPLACE PROCEDURE create_account(ACNTNUM OUT NUMBER, ACNTTYPE IN varchar2, FIRSTNAME IN varchar2, LASTNAME IN varchar2, USERNAME IN varchar2, PASSWORD IN varchar2, BALANCE IN DECIMAL)
IS
BEGIN
   INSERT INTO BANKACCOUNTS (ACNTNUM, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE) VALUES (bank_seq.nextval, ACNTTYPE, FIRSTNAME, LASTNAME, USERNAME, PASSWORD, BALANCE);
   ACNTNUM := bank_seq.currval;
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE create_trans(TRANSID OUT NUMBER, TRANS IN varchar2, AMOUNT IN DECIMAL, ACNTNUM_ID IN NUMBER)
IS
BEGIN
   INSERT INTO TRANSACTIONS (TRANSID, TRANS, AMOUNT, ACNTNUM_ID) VALUES (trans_seq.nextval, TRANS, AMOUNT, ACNTNUM_ID);
   TRANSID := trans_seq.currval;
   COMMIT;
END;